/* eslint-disable no-restricted-globals */
import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute } from "workbox-routing";

clientsClaim();
self.skipWaiting();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

// SPA navigation fallback to index.html
const handler = createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html");
registerRoute(({ request }) => request.mode === "navigate", handler);
